# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

---
title: WeBuildThis.City
timezone: America/Chicago
locale: en
collections:
  content:
    title: Content
    output: true
    permalink: "/:path/"
  departments:
    title: Departments
    output: false
  glossary:
    title: Glossary
    output: false
  projects:
    title: Projects
    output: true
  icons:
    title: icons
    output: true
    permalink: "/assets/images/:collection/:path"
defaults:
- scope:
    path: ''
  values:
    layout: 'default'
- scope:
    path: ''
    type: icons
  values:
    layout: svg
- scope:
    path: ''
    type: 'projects'
  values:
    layout: 'project'
- scope:
    path: '_content/resources'
    type: 'content'
  values:
    in_resources_menu: false
    in_permit_check_menu: false

_comments:
  department_name: The department's official name
  department_link: The link to the department's page on AustinTexas.gov
  phone: Please use the format 000-000-0000
  email:
  period_name: e.g., "General questions" or "By appointment only"
  period_time_markdown: Open-Close days and times, new lines OK
  physical_address_markdown: Actual address for visitors, new lines OK

description: The City of Austin’s Residential Permitting Resource
subtitle: Austin’s Residential Permitting Resource
show_full_navigation: true
baseurl:
url: http://alpha.webuildthis.city

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: U.S. Web Design Standards + Jekyll
description: > # this means to ignore newlines until "baseurl:"
  A boilerplate site for building prototypes and static sites with 
  the U.S. Web Design Standards. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: assets/stylesheets/
permalink: pretty
exclude:
  - /node_modules/
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - npm-debug.log
  - /css
  - /screenshots
  - /sketch-files
