# ----
# Site

title: WeBuildThis.City
subtitle: Austin’s Residential Permitting Resource
timezone: America/Chicago
show_full_navigation: true
baseurl:
url:
markdown: kramdown
description: 'The City of Austin’s Residential Permitting Resource'

sass:
    sass_dir: assets/_sass
# -----
# Build

permalink: pretty

gems:

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

collections:
  content:
    output: true
    permalink: /:path/
  contact:
    output: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
