# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

---
title: WeBuildThis.City
timezone: America/Chicago
locale: en
collections:
  content:
    title: Content
    output: true
    permalink: "/:path/"
  projects:
    title: Projects
    output: true
    permalink: "projects/:path/"
  departments:
    title: Departments
    output: false
  glossary:
    title: Glossary
    output: true
    permalink: "resources/:collection/:path"
  library:
    output: false

defaults:
- scope:
    path: ''
  values:
    layout: 'page'

# for js, which is concatenating via jekyll
- scope:
    path: 'assets'
  values:
    layout: empty

# for glossary entries
- scope:
    path: ''
    type: 'glossary'
  values:
    layout: 'glossary-entry'
    # sets up multiselect related terms for cloudcannon editor
    collections:
      - glossary
    _comments:
      term: lowercase with spaces
      short_definition: (required)
      long_definition_markdown: (required)
      source: Related Code?
      glossary: Other words commonly confused with this term

# for all content
- scope:
    path: '_content'
    type: 'content'
  values:
    layout: 'page'
    in_menu: false
    _comments:

# for project pages
- scope:
    path: '_projects'
    type: 'projects'
  values:
    layout: 'project'
    _comments:
      excerpt: Shows up on homepage. Only use on overview page
      project_name: e.g., shed, interior remodel, etc. Use the same project name for all pages associated with a project.
      in_menu: Should this show up in the header navigation and homepage? Ony use on overview page
      step_number: Order the pages of the project here, starting with 0 for overview
      overview_of_steps_title: Only use on overview page
      overview_of_steps_description: Only use on overview page
      permalink: The relative URL of the project's folder, ie "/projects/project-folder/". Only use on overview page

# for resource pages
- scope:
    path: '_content/resources'
    type: 'content'
  values:
    layout: 'page'
    _comments:

# for department listings
- scope:
    path: ''
    type: departments
  values:
    _hide_content: true
    _comments:
      department_name: The department's official name
      department_link: The url to the department's page on AustinTexas.gov
      phone: Please use the format 000-000-0000
      email_address: Only a real email address, such as office@austintexas.gov
      contact_form_url: Only a link to a contact form http://www.austintexas.gov/email/
      period_name: e.g., "General questions" or "By appointment only"
      period_time_markdown: Open-Close days and times, new lines OK

# for all pages
_comments:
  title: Title for this page (shows up in SEO) (required)

description: The City of Austin’s Residential Permitting Resource
subtitle: Austin’s Residential Permitting Resource
show_full_navigation: true
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon_path: "/assets/favicons/"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: assets/stylesheets/
permalink: pretty
exclude:
  - /node_modules/
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - npm-debug.log
  - /css
  - /screenshots
  - /sketch-files
